### ISSUE TITLE
DTBonjourServer.h not found

### ISSUE THREAD

**Issue by seeker12** [Cocoanetics/Examples#1]
I apologize in advance - I'm new to git submodules in Xcode. I'm trying to get the BonjourChat example to work. The tutorial, here: http://www.cocoanetics.com/2012/11/and-bonjour-to-you-too/, briefly describes adding DTFoundation as a git submodule, then describes the development of the BonjourChat project with no further mention of DTFoundation or how to use the DTBonjour library.

I tried adding DTBonjour as a submodule, setting up the library dependencies as described, which did produce the libDTBonjour.a products, but the BonjourChat build for iPhone simulator (6.1) fails with "DTBonjourServer.h not found", imported in BonjourChatServer.h.

I've tried setting the BonjourChat Build settings User Header Search Paths to point to the DTBonjour subproject source files, but unsuccessfully.

I expect I'm making a very silly n00b mistake. Thanks for making all your Cocoanetics work available!

**Comment by odrobnik** [comment]
The problem was probably related to your search paths. I updated everything and now it builds and runs fine.

**Comment by seeker12** [comment]
Exactly right. Thanks for the reply. It was a search path issue. When I pulled the submodule I misspelled DTFoundation as DTFoundatation. Took a while to discover. Thanks again for sharing your work. Well done!
