### ISSUE TITLE
Can't build BonjourChat example.

### ISSUE THREAD

**Issue by Maxtodont** [Cocoanetics/Examples#2]
Hi!
I couldn't build and run BonjourChat.
1. I cloned git project.
2. I updated externals (DTBonjour.xcodeproj and DTFoundation.xcodeproj).
3. Create pod files, added DTBonjour and DTFoundation libs

And I have some errors 
![2014-01-08 22 33 09](https://f.cloud.github.com/assets/5189896/1871263/4c528c60-7894-11e3-8600-32efdc7fcbf2.png)

I changed Build active architecture and valid architectures, but it didn't help

**Comment by odrobnik** [comment]
I think you must be confusing something. If you clone the Examples project recursively all is set up to work out of the box. No need to set anything up.
