### ISSUE TITLE
git submodule doesn't work

### ISSUE THREAD

**Issue by comptekki** [Cocoanetics/Examples#3]
Your instructions say to use:

git submodule update --init --recursive

but I get this error:

---

Cloning into 'Externals/DTLocalizableStringScanner'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Cocoanetics/DTLocalizableStringScanner.git' into submodule path 'Externals/DTLocalizableStringScanner' failed

---

Thanks

**Comment by odrobnik** [comment]
@comptekki Thanks for reporting this. The reason for it not working was that only I can access SSH urls on my git repos.
