### ISSUE TITLE
Expandable Table Cells.

### ISSUE THREAD

**Issue by daviddelmonte** [Cocoanetics/Examples#4]
Hi. How Do I get the DTFoundation library? This is required for the table cell example. Thanks for your hard work.

**Comment by odrobnik** [comment]
It's a git submodule.

   git clone --recursive ...

or

   git submodule update --init

**Comment by daviddelmonte** [comment]
Oops. It's been a long time since I've used Shell..

It's working fine.

On Apr 4, 2014, at 1:56 AM, Oliver Drobnik notifications@github.com wrote:

It's a git submodule.

git clone --recursive ...

or

git submodule update --init
