### ISSUE TITLE
Cocoanetics Examples - Expandable TableView Sections Issue

### ISSUE THREAD

**Issue by LuaiKalkatawi** [Cocoanetics/Examples#5]
I've downloaded Cocoanetics Examples and tried to run  Expandable TableView Sections. But there an issue that DTFoundation.xcodeproj file is not available. Could you check that please?

Thanks.

**Comment by odrobnik** [comment]
you to clone the project including submodules.

**Comment by LuaiKalkatawi** [comment]
I have cloned your project after that I run the app and I get this message "Apple.com is currently: Reachable". Shouldn't the app run?

**Comment by odrobnik** [comment]
sounds like you are starting the wrong sample.

**Comment by LuaiKalkatawi** [comment]
This is what I did;
1- Clicked on Clone on Desktop
2- Github app run and created the file to the desktop
3- I opened the file and selected ExpandableTableCells file and opened ExpandableTableCells.xcodeproj
4- run the app and just get the "Apple.com is currently: Reachable" Screen.

Please let me know if I'm missing something.

Thanks.

**Comment by odrobnik** [comment]
you are running the wrong schema. This is the Reachability app demo you are running instead of the exandable table cells.
